//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFirstWebService")]
    public interface IFirstWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWebService/Message", ReplyAction="http://tempuri.org/IFirstWebService/MessageResponse")]
        System.Threading.Tasks.Task<string> MessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWebService/Verify", ReplyAction="http://tempuri.org/IFirstWebService/VerifyResponse")]
        System.Threading.Tasks.Task<bool> VerifyAsync(string name, string cardNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWebService/VerifyFunds", ReplyAction="http://tempuri.org/IFirstWebService/VerifyFundsResponse")]
        System.Threading.Tasks.Task<bool> VerifyFundsAsync(float amount, string cardNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWebService/CusFunds", ReplyAction="http://tempuri.org/IFirstWebService/CusFundsResponse")]
        System.Threading.Tasks.Task<double> CusFundsAsync(string cardNum, double amnt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IFirstWebServiceChannel : ServiceReference1.IFirstWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class FirstWebServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IFirstWebService>, ServiceReference1.IFirstWebService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FirstWebServiceClient() : 
                base(FirstWebServiceClient.GetDefaultBinding(), FirstWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IFirstWebService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FirstWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(FirstWebServiceClient.GetBindingForEndpoint(endpointConfiguration), FirstWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FirstWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FirstWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FirstWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FirstWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FirstWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> MessageAsync()
        {
            return base.Channel.MessageAsync();
        }
        
        public System.Threading.Tasks.Task<bool> VerifyAsync(string name, string cardNum)
        {
            return base.Channel.VerifyAsync(name, cardNum);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyFundsAsync(float amount, string cardNum)
        {
            return base.Channel.VerifyFundsAsync(amount, cardNum);
        }
        
        public System.Threading.Tasks.Task<double> CusFundsAsync(string cardNum, double amnt)
        {
            return base.Channel.CusFundsAsync(cardNum, amnt);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFirstWebService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFirstWebService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:53899/FirstWebService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FirstWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IFirstWebService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FirstWebServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IFirstWebService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IFirstWebService,
        }
    }
}
